# Generated by Django 4.1.3 on 2024-02-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avantgardenapi', '0002_alter_plant_grow_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='avantgardenapi.user'),
            preserve_default=False,
        ),
    ]
